const String CREATE_TABLE_NOTE ="CREATE TABLE notes("
    "note_id TEXT, "
    "title TEXT, "
    "created_time NUMERIC, "
    "modified_time NUMERIC, "
    "tag_id TEXT"
    ")";
const String CREATE_TABLE_TAG ="CREATE TABLE tags("
    "tag_id TEXT PRIMARY KEY, "
    "name TEXT, "
    "created_time NUMERIC, "
    "modified_time NUMERIC, "
    "color TEXT, "
    ")";
const String CREATE_TABLE_NOTE_ITEM ="CREATE TABLE noteItems("
    "noteItem_id TEXT PRIMARY KEY, "
    "note_id TEXT, "
    "content TEXT, "
    "type TEXT, "
    "created_time NUMERIC, "
    "modified_time NUMERIC, "
    "textColor TEXT, "
    "bgColor TEXT"
    ")";